// src/frontend/src/lib/gratitudeMessages.ts
// Givethra — per-category gratitude messages shown on the completed-case page.
// {amount} is replaced at render time with the real amount the hero helped with.
export type GratitudeSet = { direct: string; contribution: string; unlock: string };

const GRATITUDE: Record<string, GratitudeSet> = {
  "Electricity Bill": { direct: "You cleared this family's electricity bill of {amount}. Their home is lit again because of you. May Allah light up your life just the same. \ud83e\udd32", contribution: "Your contribution of {amount} brought this family closer to keeping the lights on. Every rupee matters. Keep being a hero! \ud83e\udd32", unlock: "You unlocked this case and took the first step of a hero's journey. Browse more cases and turn your kindness into complete help! \ud83d\udcaa" },
  "Gas Bill": { direct: "You paid this family's gas bill of {amount} \u2014 a warm home and a warm meal, because of you. May your own home always be filled with warmth. \ud83e\udd32", contribution: "Your contribution of {amount} helped keep this family's home warm this month. Small acts, huge mercy. \ud83e\udd32", unlock: "You took the first step by unlocking this case. Don't stop here \u2014 your next case is waiting for a hero like you!" },
  "Water Bill": { direct: "You settled this family's water bill of {amount}. Clean water flows because of your generosity. May Allah bless your every need. \ud83e\udd32", contribution: "Your {amount} contribution helped this family access clean water. Blessed are those who give water to the thirsty. \ud83e\udd32", unlock: "You unlocked this case \u2014 the beginning of a hero's journey. Browse more cases and complete the mission!" },
  "House Rent": { direct: "You paid this family's rent of {amount}. They will live peacefully in their home for another month because of you. May your own home always be protected. \ud83e\udd32", contribution: "Your contribution of {amount} helped this family keep their roof this month. You are part of their shelter. \ud83e\udd32", unlock: "You unlocked this case and gave hope to a struggling family. Now browse and complete a full act of kindness!" },
  "School Fees": { direct: "You paid {amount} of school fees. A child's education continues because of you. May Allah grant you knowledge and blessings in return. \ud83e\udd32", contribution: "Your contribution of {amount} keeps a child in school. Every rupee is a seed of a brighter future. \ud83e\udd32", unlock: "By unlocking this case, you opened the door to a child's education. Walk through and finish what you started!" },
  "Education & Books": { direct: "You provided {amount} towards education and books. Knowledge reached a deserving mind because of you. May your own mind always stay blessed. \ud83e\udd32", contribution: "Your {amount} contribution put books in a learner's hands. Invest in knowledge, and you invest in generations. \ud83e\udd32", unlock: "You unlocked this case \u2014 now complete the journey and put real books in real hands!" },
  "Medical & Treatment": { direct: "You paid {amount} for medical treatment. A life received care because of your mercy. May Allah heal you in your time of need. \ud83e\udd32", contribution: "Your contribution of {amount} went towards saving a life. In helping the sick, you healed your own soul. \ud83e\udd32", unlock: "You unlocked a medical case \u2014 a brave first step. Now don't let this patient wait; complete your help!" },
  "Medicines": { direct: "You paid {amount} for medicines. Pain was relieved and health restored because of you. May Allah grant you perfect health. \ud83e\udd32", contribution: "Your {amount} contribution bought essential medicines for someone in pain. A simple act, a mountain of reward. \ud83e\udd32", unlock: "You unlocked this case and gave a patient hope. Complete your mission \u2014 buy the medicine that saves the day!" },
  "Food & Groceries": { direct: "You provided {amount} worth of food to a hungry family. No one slept hungry tonight because of you. May your own table always be full. \ud83e\udd32", contribution: "Your {amount} contribution filled a family's kitchen for days. Feeding the hungry is the highest charity. \ud83e\udd32", unlock: "You unlocked this case \u2014 the first step to feeding a family. Continue and let no plate stay empty!" },
  "Child Support": { direct: "You supported a child with {amount}. A child smiles and sleeps safely because of you. May Allah protect your own children. \ud83e\udd32", contribution: "Your contribution of {amount} supported an innocent child in need. The Prophet (PBUH) said: the best house is one where orphans are cared for. \ud83e\udd32", unlock: "You unlocked this case and became a child's hope. Finish strong \u2014 turn that hope into real support!" },
  "Widow & Elderly Support": { direct: "You supported a widow or elderly person with {amount}. Their dignity and comfort were preserved because of you. May Allah honor you in return. \ud83e\udd32", contribution: "Your {amount} contribution brought comfort to a widow or elder. Serving the helpless is serving Allah. \ud83e\udd32", unlock: "You unlocked this case for a widow or elder \u2014 a blessed start. Complete your help and be their strength!" },
  "Home Repair": { direct: "You paid {amount} for home repair. A family now lives in a safer home because of you. May your own home be a fortress of peace. \ud83e\udd32", contribution: "Your contribution of {amount} helped repair a damaged home. You rebuilt a family's shelter. \ud83e\udd32", unlock: "You unlocked this repair case \u2014 the first brick of a hero's work. Lay the rest and finish the house!" },
  "Disability Support": { direct: "You supported a person with disability by {amount}. Their burden was lightened because of your compassion. May Allah grant you strength. \ud83e\udd32", contribution: "Your {amount} contribution supported someone living with disability. True heroes lift those who need it most. \ud83e\udd32", unlock: "You unlocked this case \u2014 you saw a need others missed. See it through and be their helping hand!" },
  "Marriage Support": { direct: "You contributed {amount} towards a marriage. A family's joy was completed because of you. May Allah bless your own happiness. \ud83e\udd32", contribution: "Your {amount} contribution helped make a wedding possible. Sharing in joy is sharing in reward. \ud83e\udd32", unlock: "You unlocked this case to help a family celebrate. Continue and be part of their happiest day!" },
  "Business / Work Help": { direct: "You invested {amount} in someone's work and livelihood. A family now earns with dignity because of you. May your own rizq multiply. \ud83e\udd32", contribution: "Your {amount} contribution helped a small business or work opportunity survive. Helping someone earn is helping them forever. \ud83e\udd32", unlock: "You unlocked this livelihood case \u2014 the first step to someone's independence. Complete it and change a family's future!" },
  "Funeral Expenses": { direct: "You paid {amount} towards funeral expenses. A family buried their loved one with dignity because of your mercy. May Allah forgive your sins. \ud83e\udd32", contribution: "Your {amount} contribution helped honor a departed soul and ease a grieving family. The reward of this charity is immense. \ud83e\udd32", unlock: "You unlocked this case in a family's hardest moment. See it through \u2014 they will never forget your kindness." },
  "Livestock / Farming": { direct: "You supported farming/livestock with {amount}. A farmer's hope grows again because of you. May your own harvest be abundant. \ud83e\udd32", contribution: "Your {amount} contribution helped a farmer keep their livestock. Feeding the nation starts with people like you. \ud83e\udd32", unlock: "You unlocked this farming case \u2014 plant the seed of help and watch it grow. Complete your support!" },
  "Debt Relief": { direct: "You paid {amount} to relieve someone's debt. A heavy burden was lifted from their shoulders because of you. May Allah relieve your own burdens. \ud83e\udd32", contribution: "Your {amount} contribution helped free someone from the weight of debt. Relieving debtors is among the most beloved deeds. \ud83e\udd32", unlock: "You unlocked this debt-relief case \u2014 you chose mercy. Complete it and free a family from worry!" },
  "Emergency Help": { direct: "You provided {amount} in an emergency. In their darkest hour, you became their light. May Allah be your shield in emergencies. \ud83e\udd32", contribution: "Your {amount} contribution arrived exactly when it was needed most. Heroes are made in moments like this. \ud83e\udd32", unlock: "You unlocked this emergency case at a critical time. Don't stop \u2014 your help may be the lifeline they need!" },
  "Other": { direct: "You helped with {amount} in a time of need. Your silent generosity changed a life. May Allah reward you beyond measure. \ud83e\udd32", contribution: "Your contribution of {amount} made a real difference. Every act of kindness counts. Keep going! \ud83e\udd32", unlock: "You unlocked this case and chose to care. Step forward and turn your care into complete help!" },
};

const FALLBACK: GratitudeSet = {
  direct: "Thank you for completing direct help of {amount}! Because of your generosity a family's burden has been lifted. May Allah bless you! \ud83e\udd32",
  contribution: "Your generous contribution of {amount} helped complete this case! Combined with other heroes, you brought real relief. Keep being a hero! \ud83e\udd32",
  unlock: "You unlocked this case and took the first step of a hero's journey. Don't lose hope \u2014 browse more cases and make a difference! \ud83d\udcaa",
};

export function getCategoryGratitude(category?: string): GratitudeSet {
  const key = typeof category === "string" && Object.prototype.hasOwnProperty.call(GRATITUDE, category) ? category : "";
  return key ? GRATITUDE[key] : FALLBACK;
}
