// Givethra — 1Bill / direct-pay institutes list
// Bijli, Gas, Pani: company + reference type. Education/Health: 1Bill list + search + "Other".

export type UtilityCompany = { name: string; ref: string; refHint: string };

export const ELECTRICITY_COMPANIES: UtilityCompany[] = [
  { name: "K-Electric", ref: "Consumer Number", refHint: "13-digit Consumer Number (bill par 'Consumer No')" },
  { name: "LESCO (Lahore)", ref: "Reference Number", refHint: "14-digit Reference No (bill par 'Reference No')" },
  { name: "GEPCO (Gujranwala)", ref: "Reference Number", refHint: "14-digit Reference No (bill par 'Reference No')" },
  { name: "FESCO (Faisalabad)", ref: "Reference Number", refHint: "14-digit Reference No (bill par 'Reference No')" },
  { name: "MEPCO (Multan)", ref: "Reference Number", refHint: "14-digit Reference No (bill par 'Reference No')" },
  { name: "IESCO (Islamabad)", ref: "Reference Number", refHint: "14-digit Reference No (bill par 'Reference No')" },
  { name: "PESCO (Peshawar)", ref: "Reference Number", refHint: "14-digit Reference No (bill par 'Reference No')" },
  { name: "HESCO (Hyderabad)", ref: "Reference Number", refHint: "14-digit Reference No (bill par 'Reference No')" },
  { name: "SEPCO (Sukkur)", ref: "Reference Number", refHint: "14-digit Reference No (bill par 'Reference No')" },
  { name: "QESCO (Quetta)", ref: "Reference Number", refHint: "14-digit Reference No (bill par 'Reference No')" },
  { name: "TESCO (Tribal Areas)", ref: "Reference Number", refHint: "14-digit Reference No (bill par 'Reference No')" },
  { name: "HAZECO (Hazara)", ref: "Reference Number", refHint: "14-digit Reference No (bill par 'Reference No')" },
];

export const GAS_COMPANIES: UtilityCompany[] = [
  { name: "SNGPL (Sui Northern)", ref: "Consumer Number", refHint: "11-digit Consumer No (bill par 'Consumer No')" },
  { name: "SSGC (Sui Southern)", ref: "Consumer Number", refHint: "Consumer No (bill par 'Consumer No')" },
];

export const WATER_COMPANIES: UtilityCompany[] = [
  { name: "Karachi Water & Sewerage Corporation (KWSC)", ref: "Consumer Number", refHint: "Consumer No (bill par darj)" },
  { name: "Lahore WASA", ref: "Consumer / Reference Number", refHint: "Consumer/Reference No (bill par darj)" },
  { name: "Rawalpindi WASA", ref: "Consumer Number", refHint: "Consumer No (bill par darj)" },
  { name: "Faisalabad WASA", ref: "Consumer Number", refHint: "Consumer No (bill par darj)" },
  { name: "Multan WASA", ref: "Consumer Number", refHint: "Consumer No (bill par darj)" },
  { name: "Hyderabad WASA", ref: "Consumer Number", refHint: "Consumer No (bill par darj)" },
  { name: "Peshawar WSSC", ref: "Consumer Number", refHint: "Consumer No (bill par darj)" },
];

// 1Bill Education institutes (HBL list) — searchable. Reference: Fee Challan / Voucher / Roll No.
export const EDUCATION_INSTITUTES: string[] = [
  "AGAKHAN Education Student Fee",
  "UET Lahore",
  "University of Management and Technology (UMT)",
  "American Lycetuff",
  "Virtual University of Pakistan (VU)",
  "COMSATS University Islamabad",
  "COMSATS Abbottabad",
  "COMSATS University Lahore",
  "COMSATS University Islamabad - Sahiwal",
  "NUST",
  "University Of Central Punjab",
  "Lahore University of Management Sciences (LUMS)",
  "Superior Group of Colleges",
  "American Lyceum School",
  "American Lyceum International School",
  "Presbyterian Education Board",
  "Forman Christian College",
  "Benchmark School System",
  "Benchmark Education System",
  "Foundation Public School",
  "The Smart School",
  "The Smart School Gulshan Campus-II",
  "University of Sargodha",
  "University of Sargodha - Examination Fee",
  "University of Sargodha - Admission Fee",
  "University of Sargodha 2nd to Onward",
  "University of Science and Tech Bannu",
  "Bay View",
  "Hira Foundation School",
  "Hira Model School",
  "Froebel Education Centre",
  "The Lynx School",
  "The Lynx School | 8 Senior Branch",
  "The Lynx School | 8 Primary Branch",
  "The Lynx School | 8 Nursery Branch",
  "The Lynx School | 8 Daycare Branch",
  "The Lynx School S Town Nursery Branch",
  "The Lynx School S Town Senior Branch",
  "The Lynx School PWD Branch Islamabad",
  "Military College Jhelum",
  "Usman Public School",
  "Habib Schools",
  "GIKI - Existing Students",
  "GIKI - New Admission",
  "Institute of Bankers Pakistan (IBP)",
  "Iqra University",
  "Iqra University - Gulshan Campus",
  "NUMS - National University of Medical Sciences",
  "Sindh Agriculture University",
  "National College of Arts (NCA) - Admission",
  "National College of Arts (NCA) - Undergraduate",
  "National College of Arts (NCA) - Post Graduate",
  "National College of Arts (NCA) - Hostel Fee",
  "NCA Rawalpindi Under Graduate",
  "Roots Garden Schools Pvt Ltd",
  "Roots Garden Schools Pvt Ltd - RGS",
  "Roots Garden Schools Pvt Ltd - Ask-X",
  "Roots School System",
  "Roots International Schools (Private)",
  "Roots Intl Schools Pvt Ltd (DHA-XII)",
  "Roots IVY International Schools Pvt Ltd",
  "S.S Montessori",
  "SS Montessori and School",
  "Uswa College",
  "B.I.S.E Bannu",
  "B.I.S.E DI Khan",
  "B.I.S.E Malakand",
  "BISE Gujranwala",
  "BISE Lahore",
  "BISE DG Khan",
  "BISE Sahiwal",
  "BISE Sukkur",
  "BISE Rawalpindi",
  "BISE Faisalabad",
  "AJK Board of Intermediate And Secondary Education",
  "Federal Board of Intermediate and Secondary Education",
  "Board of Intermediate and Secondary Education",
  "Islamabad Career School",
  "Pakistan Testing Service Pvt Ltd",
  "Lawrence College Ghora Gali Murree",
  "Turkish Maarif Foundation (TMF)",
  "Turkish Maarif Foundation (TMF) Existing",
  "Barani Institute of Management Sciences",
  "IST Students Account",
  "KU Collection (Karachi University)",
  "KU - Semester Fee Collection",
  "Army Public School and College Barracks",
  "Army Public School and College Malir",
  "Army Public School Kharian Cantt",
  "APS Saddar Karachi Boys",
  "APS Saddar Karachi Girls",
  "APS Shahrah-e-Faisal Karachi",
  "DHA Suffa University",
  "Indus Valley School of Arts and Architecture",
  "Karachi School Of Arts",
  "Haque Academy",
  "Shah Abdul Latif University (SALU)",
  "SALU Regular Admission Fee",
  "Al Hamd Academy",
  "Denning Services Pvt Ltd",
  "IBA Karachi",
  "Mazhar Muslim Model Primary School",
  "Mazhar Muslim Model High School",
  "Mazhar Muslim Model Higher Secondary",
  "Mazhar Muslim Model Mess Ranipur",
  "Fazaia Inter College Kohat",
  "Fazaia Inter College Nur Khan",
  "Fazaia Inter College Kallar Kahar",
  "Fazaia Inter College Lowertopa",
  "Fazaia Inter College Shahbaz",
  "Fazaia Inter College Minhas Kamra",
  "Fazaia Inter College Peshawar",
  "Fazaia Degree College Risalpur",
  "Fazaia Degree College MRF Kamra",
  "Fazaia Degree College Peshawar",
  "Fazaia Degree College PAF Samungly",
  "FAZAIA DEGREE COLLEGE PAF FAISAL",
  "Fazaia Model Inter College FAZMIC",
  "FAZAIA COLLEGE LAHORE",
  "Fazaia College of Education for Women",
  "FIC Lowertopa Montessori",
  "Saleem Nawaz Fazaia College Masoor",
  "Peshawar Model Schools",
  "Peshawar Model Degree Colleges",
  "Peshawar Model Degree College Boys",
  "Peshawar Model School - Mardan",
  "SZABIST",
  "SZABUL",
  "British International School System",
  "TYMS Education Pvt Ltd",
  "Lords Educational Complex (Pvt) Ltd",
  "Muhammad College of Medicine",
  "University of the Punjab - Regular",
  "University of the Punjab - External",
  "Punjab University Gujranwala Campus",
  "City University of Science and IT",
  "Cadet College Esa Khel Entry Fee",
  "Cadet College Esa Khel College Fee",
  "Cadet College Jhang",
  "Cadet College Skardu",
  "Cadet College Hasan Abdal",
  "Frontier Corps Public School",
  "City Grammar School",
  "City Grammar School FSD",
  "FDC ARF PAC Kamra",
  "Alley Group of Colleges",
  "NDU New Students",
  "NDU Continuing Students",
  "National Defence University (NDU)",
  "501 Model School",
  "Beaconhouse School System",
  "BZU Examination Fee",
  "The Islamia University of Bahawalpur",
  "PAF College Lower Topa",
  "PAF College Sargodha",
  "Sapient Hall School",
  "University of Balochistan",
  "Super Nova School Continued Students",
  "Educational Excellence Limited",
  "University Of Gujrat",
  "Ace International Academy",
  "ACE Girls College",
  "IVY United Schools Pvt Ltd",
  "IVY College of Management Sciences",
  "Al Suffa Educational School",
  "Lahore Garrison Education System",
  "Lahore Garrison University",
  "Mashriq International School",
  "Pakistan Institute of Fashion Design",
  "BUITEMS",
  "Enamour High Schools",
  "Institute of Academic Excellence",
  "Government Associate College",
  "University of Okara",
  "Employment Processing Resource",
  "Shifa Tameer-e-Millat University",
  "National University of Technology (NUTECH)",
  "University of Sindh",
  "UET Taxila - First Semester Fee",
  "UET Taxila - Admission Processing",
  "UET Taxila - TCAT Entry Test Fee",
  "UET Taxila - Mess Fee A Hall",
  "UET Taxila - Mess Fee AB Hall",
  "UET Taxila - Mess Fee Q Hall",
  "UET Taxila - Mess Fee I Hall",
  "UET Taxila - Mess Fee Ayesha Hall",
  "The Educators",
  "The Educators Sabzazar Campus",
  "The Educators Sir Syed Campus",
  "Al Siddeeq Montessori and Secondary School",
  "Sceptre Private Limited",
  "Green Future Educational System",
  "Ghazali Model High School",
  "Meritorious Science College",
  "Meritorious Junior Campus",
  "Meritorious Schools Network",
  "Allied College of Health Sciences",
  "PECHS Girls School",
  "MPS School Fee Girls",
  "MPS Bus Fee Girls",
  "MPS Development Fee Girls",
  "Allied School Jhelum Cantt",
  "Allied School JC Campus",
  "Allied School Jhanda Chichi Campus",
  "Allied School Kasur Campus",
  "ALLIED SCHOOL JINNAH CAMPUS",
  "Allied School of Excellence Campus",
  "Allied School Excellence Campus G",
  "University of Agriculture Faisalabad",
  "Falconhouse Grammar School",
  "New Falconhouse Grammar School",
  "QUEST Larkano",
  "Quest University Nawabshah",
  "University of Poonch - Student Fees",
  "University of Poonch - Library Security",
  "University of Poonch - General Fees",
  "Sharif Educational Complex",
  "Sharif College of Engineering and Technology",
  "Sharif Model School for Girls",
  "Sharif Model School for Boys",
  "Sharif Medical and Dental College",
  "Sharif Trust",
  "Lahore Grammar School",
  "Lahore Grammar School - Gujrat Campus",
  "Lahore Grammar School - Karachi Campus",
  "Gift University",
  "National Communications Services",
  "IJK SCHOOLING SYSTEM",
  "The Shaikh Ayaz University Shikarpur",
  "Shiblee College For Women Gulberg",
  "Enablers Education System (Pvt) Ltd",
  "Dar e Arqam School FSD",
  "Dar e Arqam Shujabad",
  "DAR E ARQAM DEFENSE MARDAN",
  "DAR E ARQAM SCHOOL",
  "Aitchison College",
  "National Skills University",
  "FG Inter College Jhelum Cantt",
  "EDU Hub College of Health Sciences",
  "SPS The Eaglets",
  "SpringField School",
  "Sindh Madressatul Islam University",
  "AS SUFFAH MADINA TUL ILM ACADEMY",
  "Bahria Foundation College - North",
  "Bahria Foundation College - Central",
  "Bahria Foundation College - South",
  "Pakistan Education Services UCMS",
  "MNSUAM - Semester Fee",
  "MNSUAM - Miscellaneous Fee",
  "MNSUAM - Hostel Income",
  "MNSUAM - Transport Committee",
  "MNSUAM - Prospectus Income",
  "Treasurer MNS-UAM (FSC Pre-Agriculture)",
  "MNS UET Multan",
  "Academia Civitas",
  "SAEPN PVT LTD",
  "MHN and Company",
  "LITTLE LAMPS SCHOOL",
  "Dr AQ Khan School And College",
  "Askaria College",
  "KIET Main Campus",
  "KIET City Campus",
  "KIET North Campus",
  "Abdur Razzaq Fazala College Mianwali",
  "Al Mehran Public High School Mithi",
  "Aspire Grammar School Mirpur",
  "HHS School System",
  "St Mary High School",
  "Brightside High School",
  "CMH Kharian Medical College",
  "IIU - Student Mess",
  "IIU - Mess Hostel No 01",
  "IIU - Mess Hostel No 02",
  "IIU - Mess Hostel No 03",
  "IIU - Mess Hostel No 04",
  "IIU - Hostel Mess 5 and 6",
  "IIU - Kuwait Hostel Mess No 01",
  "International Islamic University Islamabad",
  "Hasani Academy Tayabali Boys",
  "Hasani Academy Madressah H Boys",
  "Hasani Academy FC Moriswala Girls",
  "Hasani Academy Sheikh Jeevanjee Girls",
  "iSkills",
  "Skill Development Center",
  "University of Haripur",
  "SBBUVAS Sakrand",
  "Margalla Model School",
  "Cholistan University of Veterinary Sciences",
  "Cholistan Special Education School",
  "First Step Educational System Pvt Ltd",
  "Horizon International School",
  "CAA Schools and Colleges",
  "Public School Sangota Swat",
  "Prep Steps Islamabad Private Limited",
  "Preparatory High School Pvt Ltd",
  "Chenab Education Private Limited",
  "TMUC Pvt Ltd",
  "Mohi-ud-Din Islamic University",
  "Titan College",
  "The Prep School",
  "The Prep School F Block",
  "Karakoram International University",
  "Sanai Edification Services Pvt Ltd",
  "The Pak Cromwell Education",
  "The University of Agriculture Peshawar",
  "Base Montessori MM Alam Mianwali",
  "Base Montessori PAF Base Shahbaz",
  "Mujahida Montessori",
  "Mujahida Montessori PAF Base Shahbaz",
  "Quaid e Azam Rangers School",
  "Nixor College - Clifton",
  "Nixor College - Bahadurabad",
  "Pak School System Boys High School",
  "Bagh Grammar School",
  "Cedar College",
  "Cedar School",
  "Abasyn University - Islamabad Campus",
  "Minhaj University Lahore",
  "THE Oxford School ADDA KHOI",
  "University of Kotli Azad Jammu and Kashmir",
  "University of Azad Jammu and Kashmir",
  "Suntek Education (Pvt) Ltd",
  "The Government College University",
  "Government College University Hyderabad",
  "GCWUS - Government College Women University Sialkot",
  "GSC Women University Bahawalpur",
  "Women University Multan",
  "SBK Women's University Quetta",
  "THE DREAM SCHOOL",
  "Siddeeq Public School",
  "Siddeeq Public School New Admission",
  "KUST - Admission Fee",
  "KUST - Semester Fee",
  "KUST - Affiliated College Fee",
  "Kohat University of Science and Technology",
  "PAFWA Education System Islamabad",
  "The Programmer Girls High School",
  "Silver Oaks Schools and College",
  "Liaquat College of Medicine and Dentistry",
  "Convent of Jesus and Mary School",
  "Karam Rasool Vocational Training Center",
  "Viqar Un Nisa Noon Girls Higher Secondary",
  "Mehran University of Engineering and Technology",
  "Cosmic Institute of Science and Technology",
  "University of Engineering and Technology",
  "MIUC (Private) Limited",
  "LUMHS University Jamshoro",
  "Shaheed Zulfiqar Ali Bhutto Medical University",
  "Air Base Inter College",
  "Multan University of Science and Technology",
  "Quaid-i-Azam University Islamabad",
  "Q.A.U. Fee Dues Account",
  "The Nexus Education System",
  "Preston University",
  "Pakistan Navy Educational Trust",
  "Divisional Public School And Intermediate College",
  "Headstart School Islamabad",
  "Highbrow School And College",
  "Kh. Fareed University of Engineering & IT",
  "The Institute of Chartered Accountants of Pakistan (ICAP)",
  "City School Kapco Campus",
  "Sir Syed University of Engineering",
  "Wilderness Education Systems Pvt Ltd",
  "Bilquis Postgraduate College for Women",
  "Peoples University of Medical Sciences",
  "Pakistan Institute of Engineering",
  "Humanitas Education System Private",
  "Swat Educational Complex of Modern Sciences",
  "The Radiance School System",
  "Kaizen High School",
  "AEO Enterprises Pvt Ltd",
  "The University of Mirpurkhas",
  "CPD",
  "Al Noor Welfare Trust",
  "Khadija Law College",
  "Garrison Academy Army Public School",
  "Health Services Academy",
  "University of Buner",
  "TNG Superior University",
  "B4A Education PVT LTD",
  "NCBAE",
  "STEM Education Services",
  "Aga Khan Education Service Pakistan",
  "Pakistan Institute of Development Economics (PIDE)",
  "Anmol Public School System",
  "ASAS INTERNATIONAL SCHOOL",
  "ASAS ACADEMY",
  "Lexis Academy",
  "MUX INSTITUTE",
  "Honours Kindergarten and Secondary",
  "Riphah International College",
  "National University of Technology",
  "Barani Institute of Management Sciences (2nd)",
];

// 1Bill Health institutes (list HBL app se — mazeed milne par barhate rahenge)
export const HEALTH_INSTITUTES: string[] = [
  "Liaquat National Hospital and Medical College",
  "Medicare Hospital (Private) Limited",
];

export const EDUCATION_REF_HINT = "Fee Challan / Voucher Number (challan par darj)";
export const HEALTH_REF_HINT = "Bill / Invoice / MR Number";
