import Layout from "@/components/Layout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Link } from "@tanstack/react-router";
import { ArrowRight, Search, Sparkles, Users, WalletCards } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { getDreams } from "@/lib/api";

export type Dream = {
  id: string; name: string; category: string; description: string; image_url?: string | null;
  dream_price: number; contribution_amount?: number; funded_amount: number; participant_capacity: number;
  approved_participants: number; status: string; announcement_at?: string | null;
};
export const money = (value: number) => `PKR ${Math.round(Number(value || 0)).toLocaleString()}`;
function DreamArtwork({ dream }: { dream: Dream }) {
  return <div className="relative flex h-48 items-center justify-center overflow-hidden bg-gradient-to-br from-teal-50 via-white to-amber-50">
    <div className="absolute -right-8 -top-12 h-36 w-36 rounded-full bg-teal-200/30 blur-2xl" />
    <div className="absolute -bottom-16 -left-10 h-40 w-40 rounded-full bg-amber-200/35 blur-2xl" />
    {dream.image_url ? <img src={dream.image_url} alt={dream.name} className="relative h-full w-full object-cover" /> : <div className="relative px-5 text-center text-sm font-semibold text-teal-700">Product image will appear here</div>}
    <span className="absolute left-3 top-3 rounded-full bg-white/90 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-teal-700 shadow-sm">{dream.category}</span>
  </div>;
}
export default function DreamsPage() {
  const [dreams, setDreams] = useState<Dream[]>([]); const [query, setQuery] = useState(""); const [category, setCategory] = useState("All"); const [loading, setLoading] = useState(true);
  useEffect(() => { getDreams().then(setDreams).catch(() => setDreams([])).finally(() => setLoading(false)); }, []);
  const categories = useMemo(() => ["All", ...Array.from(new Set(dreams.map((d) => d.category)))], [dreams]);
  const visible = useMemo(() => dreams.filter((d) => `${d.name} ${d.category} ${d.description}`.toLowerCase().includes(query.toLowerCase()) && (category === "All" || d.category === category)), [dreams, query, category]);
  return <Layout><main className="min-h-screen bg-gradient-to-b from-teal-50/70 via-background to-background pb-24 md:pb-10">
    <section className="relative overflow-hidden border-b border-teal-100 bg-gradient-to-br from-[#075e69] via-[#0b8795] to-[#32b6a6] text-white"><div className="absolute -right-24 -top-28 h-80 w-80 rounded-full bg-white/10 blur-3xl" /><div className="mx-auto max-w-7xl px-4 py-12 md:px-8 md:py-16"><div className="max-w-2xl"><div className="mb-4 inline-flex items-center gap-2 rounded-full bg-white/15 px-3 py-1.5 text-xs font-bold uppercase tracking-[0.18em]"><Sparkles className="h-3.5 w-3.5" /> Givethra Dreams</div><h1 className="font-display text-4xl font-black tracking-tight md:text-6xl">A meaningful step toward something you dream of.</h1><p className="mt-5 max-w-xl text-base leading-7 text-white/85 md:text-lg">Explore products listed by Givethra, see the real funding progress, and contribute an amount that works for you.</p></div><div className="mt-8 flex flex-wrap gap-3 text-sm font-semibold text-white/90"><span className="rounded-full bg-white/10 px-4 py-2"><WalletCards className="mr-2 inline h-4 w-4" />Separate from Help cases</span><span className="rounded-full bg-white/10 px-4 py-2"><Users className="mr-2 inline h-4 w-4" />Verified manual payment</span></div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-8 md:px-8"><div className="mb-7 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-teal-700">Choose your Dream</p><h2 className="mt-1 font-display text-2xl font-bold md:text-3xl">Products currently listed by Givethra</h2></div><div className="relative w-full md:w-72"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search Dreams" className="h-11 rounded-full bg-white pl-9" /></div></div><div className="mb-7 flex gap-2 overflow-x-auto pb-1">{categories.map((item) => <button key={item} type="button" onClick={() => setCategory(item)} className={`whitespace-nowrap rounded-full border px-4 py-2 text-xs font-bold transition ${item === category ? "border-teal-600 bg-teal-600 text-white" : "border-border bg-card text-muted-foreground hover:border-teal-300 hover:text-teal-700"}`}>{item}</button>)}</div>
      {loading ? <div className="rounded-3xl border bg-card p-14 text-center text-muted-foreground">Loading listed Dreams…</div> : <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{visible.map((dream) => { const percent = Math.min(100, Math.round(Number(dream.funded_amount || 0) / Math.max(1, Number(dream.dream_price || 1)) * 100)); return <article key={dream.id} className="overflow-hidden rounded-3xl border border-border bg-card shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><DreamArtwork dream={dream} /><div className="p-5"><div className="flex items-start justify-between gap-3"><h3 className="font-display text-xl font-bold leading-tight">{dream.name}</h3><span className="rounded-full bg-emerald-100 px-2 py-1 text-[10px] font-bold text-emerald-700">{dream.status}</span></div><p className="mt-2 min-h-12 text-sm leading-6 text-muted-foreground">{dream.description}</p><div className="mt-4 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Total Dream Amount</p><p className="text-xl font-black text-teal-700">{money(dream.dream_price)}</p></div><p className="text-xs font-bold text-muted-foreground">{percent}% funded</p></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-teal-100"><div className="h-full rounded-full bg-gradient-to-r from-teal-500 to-amber-400" style={{ width: `${percent}%` }} /></div><div className="mt-2 flex justify-between text-xs text-muted-foreground"><span>{money(dream.funded_amount)} funded</span><span>{money(Math.max(0, dream.dream_price - dream.funded_amount))} remaining</span></div>{dream.contribution_amount ? <p className="mt-3 text-xs font-semibold text-teal-700">Suggested contribution: {money(dream.contribution_amount)}</p> : null}<Link to="/dreams/$id" params={{ id: dream.id }} className="mt-5 block"><Button className="h-11 w-full rounded-xl bg-teal-700 font-bold hover:bg-teal-800">Make This My Dream <ArrowRight className="ml-2 h-4 w-4" /></Button></Link></div></article>; })}</div>}
      {!loading && !visible.length && <div className="rounded-3xl border border-dashed p-12 text-center text-muted-foreground">No Dream products have been listed for this view yet.</div>}
    </section></main></Layout>;
}
