import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { adminGetDreamParticipations, adminGetDreams, adminReviewDreamParticipation, adminSaveDream, uploadFileToStorage } from "@/lib/api";

const emptyForm = { name: "", category: "Car", description: "", image_url: "", actual_market_price: "", dream_price: "", participant_capacity: "100", internal_percentage_unit: "", credit_award: "0", announcement_at: "", status: "open", publication_status: "draft" };
const money = (v: any) => `PKR ${Number(v || 0).toLocaleString()}`;

export default function AdminDreamsPanel() {
  const [dreams, setDreams] = useState<any[]>([]);
  const [participations, setParticipations] = useState<any[]>([]);
  const [form, setForm] = useState<any>(emptyForm);
  const [editing, setEditing] = useState<string | undefined>();
  const [uploading, setUploading] = useState(false);
  const [busy, setBusy] = useState(false);
  const [tab, setTab] = useState<"products" | "submissions">("products");
  const load = async () => { try { const [d, p] = await Promise.all([adminGetDreams(), adminGetDreamParticipations()]); setDreams(d); setParticipations(p); } catch (e: any) { toast.error(e?.message || "Dreams could not be loaded"); } };
  useEffect(() => { void load(); }, []);
  const pending = useMemo(() => participations.filter((p) => p.status === "pending_approval"), [participations]);
  const set = (key: string, value: string) => setForm((f: any) => ({ ...f, [key]: value }));
  async function save(e: React.FormEvent) { e.preventDefault(); setBusy(true); try { await adminSaveDream({ ...form, dream_price: Number(form.dream_price), actual_market_price: form.actual_market_price === "" ? null : Number(form.actual_market_price), participant_capacity: Number(form.participant_capacity), internal_percentage_unit: form.internal_percentage_unit === "" ? null : Number(form.internal_percentage_unit), credit_award: Number(form.credit_award || 0) }, editing); toast.success(editing ? "Dream updated" : "Dream created"); setForm(emptyForm); setEditing(undefined); await load(); } catch (e: any) { toast.error(e?.message || "Could not save Dream"); } finally { setBusy(false); } }
  async function image(file: File | null) { if (!file) return; setUploading(true); try { set("image_url", await uploadFileToStorage(file, `dreams/${Date.now()}-${file.name.replace(/[^a-z0-9._-]/gi, "-")}`)); toast.success("Product image uploaded"); } catch (e: any) { toast.error(e?.message || "Image upload failed"); } finally { setUploading(false); } }
  async function review(p: any, status: string) { try { const reason = status === "rejected" ? window.prompt("Rejection reason") || "Payment proof was not approved" : undefined; await adminReviewDreamParticipation(p.id, { status, rejection_reason: reason }); toast.success(status === "approved" ? "Dream participation approved" : "Submission rejected"); await load(); } catch (e: any) { toast.error(e?.message || "Review failed"); } }
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Givethra Dreams</h2><p className="text-sm text-muted-foreground">Manage product Dreams separately from Help cases and the Credit wallet.</p></div><div className="flex gap-2"><Button variant={tab === "products" ? "default" : "outline"} onClick={() => setTab("products")}>Products ({dreams.length})</Button><Button variant={tab === "submissions" ? "default" : "outline"} onClick={() => setTab("submissions")}>Payment submissions {pending.length > 0 && `(${pending.length})`}</Button></div></div>
    {tab === "products" ? <div className="grid gap-5 lg:grid-cols-[360px_1fr]">
      <form onSubmit={save} className="space-y-3 rounded-2xl border bg-card p-4"><h3 className="font-semibold">{editing ? "Edit Dream" : "Add New Dream"}</h3><Input placeholder="Product name" value={form.name} onChange={e => set("name", e.target.value)} required /><Input placeholder="Category (e.g. Car, TV)" value={form.category} onChange={e => set("category", e.target.value)} required /><Textarea placeholder="Public Dream description" value={form.description} onChange={e => set("description", e.target.value)} required /><label className="grid gap-1 text-xs font-semibold">Product image<input type="file" accept="image/*" onChange={e => void image(e.target.files?.[0] || null)} className="text-xs" /></label>{form.image_url && <img src={form.image_url} alt="Dream product" className="h-24 w-full rounded-lg object-cover" />}<Input placeholder="Actual market price (admin only)" inputMode="numeric" value={form.actual_market_price} onChange={e => set("actual_market_price", e.target.value)} /><Input placeholder="Givethra Dream Price" inputMode="numeric" value={form.dream_price} onChange={e => set("dream_price", e.target.value)} required /><div className="grid grid-cols-2 gap-2"><Input placeholder="Capacity" inputMode="numeric" value={form.participant_capacity} onChange={e => set("participant_capacity", e.target.value)} /><Input placeholder="Credit award" inputMode="numeric" value={form.credit_award} onChange={e => set("credit_award", e.target.value)} /></div><Input placeholder="Internal percentage unit (admin only)" value={form.internal_percentage_unit} onChange={e => set("internal_percentage_unit", e.target.value)} /><Input type="datetime-local" value={form.announcement_at} onChange={e => set("announcement_at", e.target.value)} /><div className="grid grid-cols-2 gap-2"><select className="h-10 rounded-md border bg-background px-3 text-sm" value={form.status} onChange={e => set("status", e.target.value)}><option value="open">Open</option><option value="active">Active</option><option value="closed">Closed</option><option value="completed">Completed</option></select><select className="h-10 rounded-md border bg-background px-3 text-sm" value={form.publication_status} onChange={e => set("publication_status", e.target.value)}><option value="draft">Draft</option><option value="published">Published</option><option value="unpublished">Unpublished</option></select></div><div className="flex gap-2"><Button type="submit" disabled={busy || uploading} className="flex-1">{busy ? "Saving…" : editing ? "Update Dream" : "Add Dream"}</Button>{editing && <Button type="button" variant="outline" onClick={() => { setEditing(undefined); setForm(emptyForm); }}>Cancel</Button>}</div></form>
      <div className="space-y-3">{dreams.map(d => { const percent = Math.min(100, Math.round(Number(d.funded_amount || 0) / Math.max(1, Number(d.dream_price || 1)) * 100)); return <div key={d.id} className="rounded-2xl border bg-card p-4"><div className="flex gap-4">{d.image_url ? <img src={d.image_url} alt={d.name} className="h-20 w-24 rounded-lg object-cover" /> : <div className="grid h-20 w-24 place-items-center rounded-lg bg-teal-50 text-3xl">✨</div>}<div className="min-w-0 flex-1"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-bold">{d.name}</h3><span className="rounded-full bg-muted px-2 py-0.5 text-xs">{d.publication_status} · {d.status}</span></div><p className="text-xs text-muted-foreground">{d.category} · Dream Price {money(d.dream_price)} · Admin market price {money(d.actual_market_price)}</p><div className="mt-2 h-2 rounded-full bg-teal-100"><div className="h-full rounded-full bg-teal-600" style={{ width: `${percent}%` }} /></div><p className="mt-1 text-xs text-muted-foreground">{percent}% funded · {d.approved_participants || 0} approved · {d.pending_participants || 0} pending</p></div></div><Button size="sm" variant="outline" className="mt-3" onClick={() => { setEditing(d.id); setForm({ ...emptyForm, ...d, actual_market_price: d.actual_market_price ?? "", dream_price: d.dream_price ?? "", participant_capacity: d.participant_capacity ?? "", internal_percentage_unit: d.internal_percentage_unit ?? "", credit_award: d.credit_award ?? "" }); }}>Edit details</Button></div>})}</div>
    </div> : <div className="space-y-3">{participations.length === 0 ? <div className="rounded-2xl border border-dashed p-10 text-center text-muted-foreground">No Dream payment submissions yet.</div> : participations.map(p => <div key={p.id} className="rounded-2xl border bg-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold">{p.dream_name}</h3><p className="text-sm">{p.user_name || p.email || p.user_id} · {money(p.contribution_amount)} · <span className="font-semibold capitalize">{String(p.status).replaceAll("_", " ")}</span></p><p className="text-xs text-muted-foreground">{p.payment_method || "Payment method not entered"} · TXN {p.transaction_id} · {p.created_at ? new Date(p.created_at).toLocaleString() : "—"}</p>{p.full_name && <p className="mt-1 text-xs">Name: {p.full_name} {p.mobile_number ? `· Mobile: ${p.mobile_number}` : ""}</p>}{p.proof_url && <a href={p.proof_url} target="_blank" rel="noreferrer" className="mt-2 inline-block text-sm font-semibold text-primary underline">View payment receipt</a>}</div>{p.status === "pending_approval" && <div className="flex gap-2"><Button size="sm" onClick={() => void review(p, "approved")}>Approve</Button><Button size="sm" variant="outline" className="text-red-600" onClick={() => void review(p, "rejected")}>Reject</Button></div>}</div></div>)}</div>}
  </div>;
}
