/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const FileRef = IDL.Record({
  'mimeType' : IDL.Text,
  'fileName' : IDL.Text,
  'storageId' : IDL.Text,
});
export const UserId = IDL.Principal;
export const KycStatus = IDL.Variant({
  'UnderReview' : IDL.Null,
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Country = IDL.Text;
export const Timestamp = IDL.Int;
export const Role = IDL.Variant({
  'Hero' : IDL.Null,
  'HelpSeeker' : IDL.Null,
  'Admin' : IDL.Null,
});
export const UserPublic = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'timezone' : IDL.Text,
  'preferredLanguage' : IDL.Text,
  'country' : Country,
  'lastLoginAt' : IDL.Int,
  'city' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : Role,
  'fullName' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'kycStatus' : KycStatus,
  'avatarRef' : IDL.Opt(FileRef),
  'phoneNumber' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Achievement = IDL.Variant({
  'TrustedHero' : IDL.Null,
  'FirstSupport' : IDL.Null,
  'TenPeopleHelped' : IDL.Null,
  'EducationHero' : IDL.Null,
  'MedicalHero' : IDL.Null,
  'CommunityHero' : IDL.Null,
  'FiftyPeopleHelped' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Confirmed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const FeeType = IDL.Variant({
  'ListingFee' : IDL.Null,
  'UnlockFee' : IDL.Null,
});
export const USDCents = IDL.Nat;
export const PaymentPublic = IDL.Record({
  'id' : IDL.Nat,
  'status' : PaymentStatus,
  'createdAt' : Timestamp,
  'feeType' : FeeType,
  'amountCents' : USDCents,
  'caseId' : IDL.Opt(IDL.Nat),
  'stripeSessionId' : IDL.Text,
  'paidBy' : UserId,
});
export const Category = IDL.Variant({
  'Surgery' : IDL.Null,
  'Orphans' : IDL.Null,
  'Food' : IDL.Null,
  'DebtRelief' : IDL.Null,
  'Books' : IDL.Null,
  'EmergencyNeeds' : IDL.Null,
  'Widows' : IDL.Null,
  'Uniform' : IDL.Null,
  'Medicines' : IDL.Null,
  'Employment' : IDL.Null,
  'DisabilitySupport' : IDL.Null,
  'Medical' : IDL.Null,
  'Housing' : IDL.Null,
  'Transportation' : IDL.Null,
  'UniversityFees' : IDL.Null,
  'Other' : IDL.Null,
  'SchoolFees' : IDL.Null,
  'Education' : IDL.Null,
  'Utilities' : IDL.Null,
});
export const City = IDL.Text;
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const VerificationStatus = IDL.Variant({
  'DocumentsSubmitted' : IDL.Null,
  'InstitutionVerified' : IDL.Null,
  'Unverified' : IDL.Null,
});
export const CasePublic = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'documents' : IDL.Vec(FileRef),
  'country' : Country,
  'city' : City,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : IDL.Text,
  'deadline' : Timestamp,
  'adminNote' : IDL.Opt(IDL.Text),
  'amountNeeded' : USDCents,
  'category' : Category,
  'isPublic' : IDL.Bool,
  'verificationStatus' : VerificationStatus,
});
export const ReviewStatus = IDL.Variant({
  'UnderReview' : IDL.Null,
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Submitted' : IDL.Null,
  'Completed' : IDL.Null,
});
export const SupportProofPublic = IDL.Record({
  'id' : IDL.Nat,
  'files' : IDL.Vec(FileRef),
  'status' : ReviewStatus,
  'heroId' : UserId,
  'referenceNumber' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'adminNote' : IDL.Opt(IDL.Text),
  'caseId' : IDL.Nat,
});
export const CaseSummary = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'country' : Country,
  'city' : City,
  'createdAt' : Timestamp,
  'deadline' : Timestamp,
  'amountNeeded' : USDCents,
  'category' : Category,
  'verificationStatus' : VerificationStatus,
});
export const MessagePublic = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'conversationId' : IDL.Nat,
  'receiverId' : UserId,
  'caseId' : IDL.Opt(IDL.Nat),
  'senderId' : UserId,
});
export const HelpSeekerStatsPublic = IDL.Record({
  'requestsSubmitted' : IDL.Nat,
  'requestsCompleted' : IDL.Nat,
  'requestsApproved' : IDL.Nat,
});
export const HeroStatsPublic = IDL.Record({
  'peopleHelped' : IDL.Nat,
  'casesSupported' : IDL.Nat,
  'proudHeartCount' : IDL.Nat,
  'casesCompleted' : IDL.Nat,
  'achievements' : IDL.Vec(Achievement),
});
export const LoginDevice = IDL.Record({
  'id' : IDL.Text,
  'os' : IDL.Text,
  'deviceName' : IDL.Text,
  'lastAccess' : IDL.Int,
  'ipAddress' : IDL.Text,
});
export const ConversationPublic = IDL.Record({
  'id' : IDL.Nat,
  'lastMessageContent' : IDL.Opt(IDL.Text),
  'lastMessageAt' : IDL.Opt(Timestamp),
  'unreadCount' : IDL.Nat,
  'caseId' : IDL.Opt(IDL.Nat),
  'participantIds' : IDL.Vec(UserId),
});
export const NotificationType = IDL.Variant({
  'CaseApproved' : IDL.Null,
  'VerificationUpdate' : IDL.Null,
  'CaseRejected' : IDL.Null,
  'SupportSubmitted' : IDL.Null,
  'UnlockPurchased' : IDL.Null,
  'NewMessage' : IDL.Null,
  'ProudHeartReceived' : IDL.Null,
});
export const NotificationPublic = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'relatedUserId' : IDL.Opt(UserId),
  'notifType' : NotificationType,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'relatedCaseId' : IDL.Opt(IDL.Nat),
  'message' : IDL.Text,
});
export const PlatformStats = IDL.Record({
  'totalCases' : IDL.Nat,
  'totalSupportDistributed' : IDL.Nat,
  'totalHeroes' : IDL.Nat,
  'totalCompletedCases' : IDL.Nat,
});
export const PrivacySettingsPublic = IDL.Record({
  'profileVisibility' : IDL.Text,
  'inAppNotificationsEnabled' : IDL.Bool,
  'countryVisibility' : IDL.Bool,
  'emailNotificationsEnabled' : IDL.Bool,
  'activityVisibility' : IDL.Bool,
  'caseUpdatesEnabled' : IDL.Bool,
});
export const ProudHeart = IDL.Record({
  'fromHelpSeeker' : UserId,
  'toHero' : UserId,
  'awardedAt' : Timestamp,
  'caseId' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const CreditTxnKind = IDL.Variant({
  'SpentOnUnlock' : IDL.Null,
  'SpentOnCase' : IDL.Null,
  'Purchase' : IDL.Null,
  'AdminGrant' : IDL.Null,
});
export const CreditTransaction = IDL.Record({
  'id' : IDL.Nat,
  'userId' : UserId,
  'kind' : CreditTxnKind,
  'note' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'amount' : IDL.Int,
});
export const UserSettingsPublic = IDL.Record({
  'timezone' : IDL.Text,
  'theme' : IDL.Text,
  'weeklyDigest' : IDL.Bool,
  'emailNotifications' : IDL.Bool,
  'inAppNotifications' : IDL.Bool,
  'language' : IDL.Text,
  'largerText' : IDL.Bool,
  'currencyDisplay' : IDL.Text,
  'highContrast' : IDL.Bool,
  'reducedAnimations' : IDL.Bool,
});
export const PageRequest = IDL.Record({
  'offset' : IDL.Nat,
  'limit' : IDL.Nat,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addCaseDocument' : IDL.Func([IDL.Nat, FileRef], [], []),
  'adminGrantCredits' : IDL.Func([UserId, IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  'adminUpdateKycStatus' : IDL.Func([UserId, KycStatus], [UserPublic], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'awardProudHeart' : IDL.Func([IDL.Nat, UserId], [], []),
  'banUser' : IDL.Func([UserId], [], []),
  'computeAchievements' : IDL.Func([UserId], [IDL.Vec(Achievement)], ['query']),
  'confirmCreditPurchase' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'confirmListingFee' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat)],
      [PaymentPublic],
      [],
    ),
  'confirmUnlockFee' : IDL.Func([IDL.Text, IDL.Nat], [PaymentPublic], []),
  'createCase' : IDL.Func(
      [IDL.Text, IDL.Text, Category, Country, City, USDCents, Timestamp],
      [IDL.Nat],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createCreditPurchaseSession' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createListingFeeSession' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'createUnlockFeeSession' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'dismissNotification' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllCases' : IDL.Func([], [IDL.Vec(CasePublic)], ['query']),
  'getAllProofs' : IDL.Func([], [IDL.Vec(SupportProofPublic)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserPublic)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserPublic)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCaseDetail' : IDL.Func([IDL.Nat], [IDL.Opt(CasePublic)], ['query']),
  'getCaseSummary' : IDL.Func([IDL.Nat], [IDL.Opt(CaseSummary)], ['query']),
  'getConversationMessages' : IDL.Func([IDL.Nat], [IDL.Vec(MessagePublic)], []),
  'getHelpSeekerStats' : IDL.Func(
      [UserId],
      [IDL.Opt(HelpSeekerStatsPublic)],
      ['query'],
    ),
  'getHeroStats' : IDL.Func([UserId], [IDL.Opt(HeroStatsPublic)], ['query']),
  'getLoginDevices' : IDL.Func([], [IDL.Vec(LoginDevice)], ['query']),
  'getMyConversations' : IDL.Func([], [IDL.Vec(ConversationPublic)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(NotificationPublic)], ['query']),
  'getMyProofs' : IDL.Func([], [IDL.Vec(SupportProofPublic)], ['query']),
  'getMySupportedCases' : IDL.Func([], [IDL.Vec(CaseSummary)], ['query']),
  'getMyTrustScore' : IDL.Func([], [IDL.Nat], ['query']),
  'getPendingPayments' : IDL.Func([], [IDL.Vec(PaymentPublic)], ['query']),
  'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
  'getPrivacySettings' : IDL.Func(
      [],
      [IDL.Opt(PrivacySettingsPublic)],
      ['query'],
    ),
  'getProofsForCase' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SupportProofPublic)],
      ['query'],
    ),
  'getProudHeartsForHero' : IDL.Func(
      [UserId],
      [IDL.Vec(ProudHeart)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTransactionHistory' : IDL.Func(
      [],
      [IDL.Vec(CreditTransaction)],
      ['query'],
    ),
  'getUnreadMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUser' : IDL.Func([UserId], [IDL.Opt(UserPublic)], ['query']),
  'getUserSettings' : IDL.Func([], [IDL.Opt(UserSettingsPublic)], ['query']),
  'getWallet' : IDL.Func([], [IDL.Int], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isUnlocked' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'listCases' : IDL.Func(
      [IDL.Opt(Category), PageRequest],
      [IDL.Vec(CaseSummary)],
      ['query'],
    ),
  'logoutAllOtherDevices' : IDL.Func([], [IDL.Nat], []),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, Role], [UserPublic], []),
  'requestAccountDeletion' : IDL.Func([], [IDL.Text], []),
  'requestDataDownload' : IDL.Func([], [IDL.Text], []),
  'sendMessage' : IDL.Func(
      [UserId, IDL.Opt(IDL.Nat), IDL.Text],
      [MessagePublic],
      [],
    ),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitProof' : IDL.Func(
      [IDL.Nat, IDL.Vec(FileRef), IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'suspendUser' : IDL.Func([UserId], [], []),
  'switchRole' : IDL.Func([Role], [UserPublic], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unlockCase' : IDL.Func([IDL.Nat], [], []),
  'updatePrivacySettings' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool],
      [PrivacySettingsPublic],
      [],
    ),
  'updateProofStatus' : IDL.Func(
      [IDL.Nat, ReviewStatus, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateUserProfile' : IDL.Func(
      [IDL.Text, Country, IDL.Opt(FileRef)],
      [UserPublic],
      [],
    ),
  'updateUserProfileExtended' : IDL.Func(
      [
        IDL.Text,
        Country,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(FileRef),
      ],
      [UserPublic],
      [],
    ),
  'updateUserSettings' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
      ],
      [UserSettingsPublic],
      [],
    ),
  'updateVerificationStatus' : IDL.Func([IDL.Nat, VerificationStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const FileRef = IDL.Record({
    'mimeType' : IDL.Text,
    'fileName' : IDL.Text,
    'storageId' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const KycStatus = IDL.Variant({
    'UnderReview' : IDL.Null,
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Country = IDL.Text;
  const Timestamp = IDL.Int;
  const Role = IDL.Variant({
    'Hero' : IDL.Null,
    'HelpSeeker' : IDL.Null,
    'Admin' : IDL.Null,
  });
  const UserPublic = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'timezone' : IDL.Text,
    'preferredLanguage' : IDL.Text,
    'country' : Country,
    'lastLoginAt' : IDL.Int,
    'city' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : Role,
    'fullName' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'kycStatus' : KycStatus,
    'avatarRef' : IDL.Opt(FileRef),
    'phoneNumber' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Achievement = IDL.Variant({
    'TrustedHero' : IDL.Null,
    'FirstSupport' : IDL.Null,
    'TenPeopleHelped' : IDL.Null,
    'EducationHero' : IDL.Null,
    'MedicalHero' : IDL.Null,
    'CommunityHero' : IDL.Null,
    'FiftyPeopleHelped' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Confirmed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const FeeType = IDL.Variant({
    'ListingFee' : IDL.Null,
    'UnlockFee' : IDL.Null,
  });
  const USDCents = IDL.Nat;
  const PaymentPublic = IDL.Record({
    'id' : IDL.Nat,
    'status' : PaymentStatus,
    'createdAt' : Timestamp,
    'feeType' : FeeType,
    'amountCents' : USDCents,
    'caseId' : IDL.Opt(IDL.Nat),
    'stripeSessionId' : IDL.Text,
    'paidBy' : UserId,
  });
  const Category = IDL.Variant({
    'Surgery' : IDL.Null,
    'Orphans' : IDL.Null,
    'Food' : IDL.Null,
    'DebtRelief' : IDL.Null,
    'Books' : IDL.Null,
    'EmergencyNeeds' : IDL.Null,
    'Widows' : IDL.Null,
    'Uniform' : IDL.Null,
    'Medicines' : IDL.Null,
    'Employment' : IDL.Null,
    'DisabilitySupport' : IDL.Null,
    'Medical' : IDL.Null,
    'Housing' : IDL.Null,
    'Transportation' : IDL.Null,
    'UniversityFees' : IDL.Null,
    'Other' : IDL.Null,
    'SchoolFees' : IDL.Null,
    'Education' : IDL.Null,
    'Utilities' : IDL.Null,
  });
  const City = IDL.Text;
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const VerificationStatus = IDL.Variant({
    'DocumentsSubmitted' : IDL.Null,
    'InstitutionVerified' : IDL.Null,
    'Unverified' : IDL.Null,
  });
  const CasePublic = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'documents' : IDL.Vec(FileRef),
    'country' : Country,
    'city' : City,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'description' : IDL.Text,
    'deadline' : Timestamp,
    'adminNote' : IDL.Opt(IDL.Text),
    'amountNeeded' : USDCents,
    'category' : Category,
    'isPublic' : IDL.Bool,
    'verificationStatus' : VerificationStatus,
  });
  const ReviewStatus = IDL.Variant({
    'UnderReview' : IDL.Null,
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Submitted' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const SupportProofPublic = IDL.Record({
    'id' : IDL.Nat,
    'files' : IDL.Vec(FileRef),
    'status' : ReviewStatus,
    'heroId' : UserId,
    'referenceNumber' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'adminNote' : IDL.Opt(IDL.Text),
    'caseId' : IDL.Nat,
  });
  const CaseSummary = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'country' : Country,
    'city' : City,
    'createdAt' : Timestamp,
    'deadline' : Timestamp,
    'amountNeeded' : USDCents,
    'category' : Category,
    'verificationStatus' : VerificationStatus,
  });
  const MessagePublic = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'conversationId' : IDL.Nat,
    'receiverId' : UserId,
    'caseId' : IDL.Opt(IDL.Nat),
    'senderId' : UserId,
  });
  const HelpSeekerStatsPublic = IDL.Record({
    'requestsSubmitted' : IDL.Nat,
    'requestsCompleted' : IDL.Nat,
    'requestsApproved' : IDL.Nat,
  });
  const HeroStatsPublic = IDL.Record({
    'peopleHelped' : IDL.Nat,
    'casesSupported' : IDL.Nat,
    'proudHeartCount' : IDL.Nat,
    'casesCompleted' : IDL.Nat,
    'achievements' : IDL.Vec(Achievement),
  });
  const LoginDevice = IDL.Record({
    'id' : IDL.Text,
    'os' : IDL.Text,
    'deviceName' : IDL.Text,
    'lastAccess' : IDL.Int,
    'ipAddress' : IDL.Text,
  });
  const ConversationPublic = IDL.Record({
    'id' : IDL.Nat,
    'lastMessageContent' : IDL.Opt(IDL.Text),
    'lastMessageAt' : IDL.Opt(Timestamp),
    'unreadCount' : IDL.Nat,
    'caseId' : IDL.Opt(IDL.Nat),
    'participantIds' : IDL.Vec(UserId),
  });
  const NotificationType = IDL.Variant({
    'CaseApproved' : IDL.Null,
    'VerificationUpdate' : IDL.Null,
    'CaseRejected' : IDL.Null,
    'SupportSubmitted' : IDL.Null,
    'UnlockPurchased' : IDL.Null,
    'NewMessage' : IDL.Null,
    'ProudHeartReceived' : IDL.Null,
  });
  const NotificationPublic = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'relatedUserId' : IDL.Opt(UserId),
    'notifType' : NotificationType,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'relatedCaseId' : IDL.Opt(IDL.Nat),
    'message' : IDL.Text,
  });
  const PlatformStats = IDL.Record({
    'totalCases' : IDL.Nat,
    'totalSupportDistributed' : IDL.Nat,
    'totalHeroes' : IDL.Nat,
    'totalCompletedCases' : IDL.Nat,
  });
  const PrivacySettingsPublic = IDL.Record({
    'profileVisibility' : IDL.Text,
    'inAppNotificationsEnabled' : IDL.Bool,
    'countryVisibility' : IDL.Bool,
    'emailNotificationsEnabled' : IDL.Bool,
    'activityVisibility' : IDL.Bool,
    'caseUpdatesEnabled' : IDL.Bool,
  });
  const ProudHeart = IDL.Record({
    'fromHelpSeeker' : UserId,
    'toHero' : UserId,
    'awardedAt' : Timestamp,
    'caseId' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const CreditTxnKind = IDL.Variant({
    'SpentOnUnlock' : IDL.Null,
    'SpentOnCase' : IDL.Null,
    'Purchase' : IDL.Null,
    'AdminGrant' : IDL.Null,
  });
  const CreditTransaction = IDL.Record({
    'id' : IDL.Nat,
    'userId' : UserId,
    'kind' : CreditTxnKind,
    'note' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'amount' : IDL.Int,
  });
  const UserSettingsPublic = IDL.Record({
    'timezone' : IDL.Text,
    'theme' : IDL.Text,
    'weeklyDigest' : IDL.Bool,
    'emailNotifications' : IDL.Bool,
    'inAppNotifications' : IDL.Bool,
    'language' : IDL.Text,
    'largerText' : IDL.Bool,
    'currencyDisplay' : IDL.Text,
    'highContrast' : IDL.Bool,
    'reducedAnimations' : IDL.Bool,
  });
  const PageRequest = IDL.Record({ 'offset' : IDL.Nat, 'limit' : IDL.Nat });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addCaseDocument' : IDL.Func([IDL.Nat, FileRef], [], []),
    'adminGrantCredits' : IDL.Func(
        [UserId, IDL.Nat, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'adminUpdateKycStatus' : IDL.Func([UserId, KycStatus], [UserPublic], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'awardProudHeart' : IDL.Func([IDL.Nat, UserId], [], []),
    'banUser' : IDL.Func([UserId], [], []),
    'computeAchievements' : IDL.Func(
        [UserId],
        [IDL.Vec(Achievement)],
        ['query'],
      ),
    'confirmCreditPurchase' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'confirmListingFee' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat)],
        [PaymentPublic],
        [],
      ),
    'confirmUnlockFee' : IDL.Func([IDL.Text, IDL.Nat], [PaymentPublic], []),
    'createCase' : IDL.Func(
        [IDL.Text, IDL.Text, Category, Country, City, USDCents, Timestamp],
        [IDL.Nat],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCreditPurchaseSession' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createListingFeeSession' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'createUnlockFeeSession' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'dismissNotification' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllCases' : IDL.Func([], [IDL.Vec(CasePublic)], ['query']),
    'getAllProofs' : IDL.Func([], [IDL.Vec(SupportProofPublic)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserPublic)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserPublic)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCaseDetail' : IDL.Func([IDL.Nat], [IDL.Opt(CasePublic)], ['query']),
    'getCaseSummary' : IDL.Func([IDL.Nat], [IDL.Opt(CaseSummary)], ['query']),
    'getConversationMessages' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MessagePublic)],
        [],
      ),
    'getHelpSeekerStats' : IDL.Func(
        [UserId],
        [IDL.Opt(HelpSeekerStatsPublic)],
        ['query'],
      ),
    'getHeroStats' : IDL.Func([UserId], [IDL.Opt(HeroStatsPublic)], ['query']),
    'getLoginDevices' : IDL.Func([], [IDL.Vec(LoginDevice)], ['query']),
    'getMyConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationPublic)],
        ['query'],
      ),
    'getMyNotifications' : IDL.Func(
        [],
        [IDL.Vec(NotificationPublic)],
        ['query'],
      ),
    'getMyProofs' : IDL.Func([], [IDL.Vec(SupportProofPublic)], ['query']),
    'getMySupportedCases' : IDL.Func([], [IDL.Vec(CaseSummary)], ['query']),
    'getMyTrustScore' : IDL.Func([], [IDL.Nat], ['query']),
    'getPendingPayments' : IDL.Func([], [IDL.Vec(PaymentPublic)], ['query']),
    'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
    'getPrivacySettings' : IDL.Func(
        [],
        [IDL.Opt(PrivacySettingsPublic)],
        ['query'],
      ),
    'getProofsForCase' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SupportProofPublic)],
        ['query'],
      ),
    'getProudHeartsForHero' : IDL.Func(
        [UserId],
        [IDL.Vec(ProudHeart)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTransactionHistory' : IDL.Func(
        [],
        [IDL.Vec(CreditTransaction)],
        ['query'],
      ),
    'getUnreadMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUser' : IDL.Func([UserId], [IDL.Opt(UserPublic)], ['query']),
    'getUserSettings' : IDL.Func([], [IDL.Opt(UserSettingsPublic)], ['query']),
    'getWallet' : IDL.Func([], [IDL.Int], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isUnlocked' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'listCases' : IDL.Func(
        [IDL.Opt(Category), PageRequest],
        [IDL.Vec(CaseSummary)],
        ['query'],
      ),
    'logoutAllOtherDevices' : IDL.Func([], [IDL.Nat], []),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, Role], [UserPublic], []),
    'requestAccountDeletion' : IDL.Func([], [IDL.Text], []),
    'requestDataDownload' : IDL.Func([], [IDL.Text], []),
    'sendMessage' : IDL.Func(
        [UserId, IDL.Opt(IDL.Nat), IDL.Text],
        [MessagePublic],
        [],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitProof' : IDL.Func(
        [IDL.Nat, IDL.Vec(FileRef), IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'suspendUser' : IDL.Func([UserId], [], []),
    'switchRole' : IDL.Func([Role], [UserPublic], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unlockCase' : IDL.Func([IDL.Nat], [], []),
    'updatePrivacySettings' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool],
        [PrivacySettingsPublic],
        [],
      ),
    'updateProofStatus' : IDL.Func(
        [IDL.Nat, ReviewStatus, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateUserProfile' : IDL.Func(
        [IDL.Text, Country, IDL.Opt(FileRef)],
        [UserPublic],
        [],
      ),
    'updateUserProfileExtended' : IDL.Func(
        [
          IDL.Text,
          Country,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(FileRef),
        ],
        [UserPublic],
        [],
      ),
    'updateUserSettings' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
        ],
        [UserSettingsPublic],
        [],
      ),
    'updateVerificationStatus' : IDL.Func(
        [IDL.Nat, VerificationStatus],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };