/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Achievement = { 'TrustedHero' : null } |
  { 'FirstSupport' : null } |
  { 'TenPeopleHelped' : null } |
  { 'EducationHero' : null } |
  { 'MedicalHero' : null } |
  { 'CommunityHero' : null } |
  { 'FiftyPeopleHelped' : null };
export interface CasePublic {
  'id' : bigint,
  'title' : string,
  'documents' : Array<FileRef>,
  'country' : Country,
  'city' : City,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : string,
  'deadline' : Timestamp,
  'adminNote' : [] | [string],
  'amountNeeded' : USDCents,
  'category' : Category,
  'isPublic' : boolean,
  'verificationStatus' : VerificationStatus,
}
export interface CaseSummary {
  'id' : bigint,
  'title' : string,
  'country' : Country,
  'city' : City,
  'createdAt' : Timestamp,
  'deadline' : Timestamp,
  'amountNeeded' : USDCents,
  'category' : Category,
  'verificationStatus' : VerificationStatus,
}
export type Category = { 'Surgery' : null } |
  { 'Orphans' : null } |
  { 'Food' : null } |
  { 'DebtRelief' : null } |
  { 'Books' : null } |
  { 'EmergencyNeeds' : null } |
  { 'Widows' : null } |
  { 'Uniform' : null } |
  { 'Medicines' : null } |
  { 'Employment' : null } |
  { 'DisabilitySupport' : null } |
  { 'Medical' : null } |
  { 'Housing' : null } |
  { 'Transportation' : null } |
  { 'UniversityFees' : null } |
  { 'Other' : null } |
  { 'SchoolFees' : null } |
  { 'Education' : null } |
  { 'Utilities' : null };
export type City = string;
export interface ConversationPublic {
  'id' : bigint,
  'lastMessageContent' : [] | [string],
  'lastMessageAt' : [] | [Timestamp],
  'unreadCount' : bigint,
  'caseId' : [] | [bigint],
  'participantIds' : Array<UserId>,
}
export type Country = string;
export interface CreditTransaction {
  'id' : bigint,
  'userId' : UserId,
  'kind' : CreditTxnKind,
  'note' : [] | [string],
  'createdAt' : Timestamp,
  'amount' : bigint,
}
export type CreditTxnKind = { 'SpentOnUnlock' : null } |
  { 'SpentOnCase' : null } |
  { 'Purchase' : null } |
  { 'AdminGrant' : null };
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type FeeType = { 'ListingFee' : null } |
  { 'UnlockFee' : null };
export interface FileRef {
  'mimeType' : string,
  'fileName' : string,
  'storageId' : string,
}
export interface HelpSeekerStatsPublic {
  'requestsSubmitted' : bigint,
  'requestsCompleted' : bigint,
  'requestsApproved' : bigint,
}
export interface HeroStatsPublic {
  'peopleHelped' : bigint,
  'casesSupported' : bigint,
  'proudHeartCount' : bigint,
  'casesCompleted' : bigint,
  'achievements' : Array<Achievement>,
}
export type KycStatus = { 'UnderReview' : null } |
  { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface LoginDevice {
  'id' : string,
  'os' : string,
  'deviceName' : string,
  'lastAccess' : bigint,
  'ipAddress' : string,
}
export interface MessagePublic {
  'id' : bigint,
  'content' : string,
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'conversationId' : bigint,
  'receiverId' : UserId,
  'caseId' : [] | [bigint],
  'senderId' : UserId,
}
export interface NotificationPublic {
  'id' : bigint,
  'title' : string,
  'relatedUserId' : [] | [UserId],
  'notifType' : NotificationType,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'relatedCaseId' : [] | [bigint],
  'message' : string,
}
export type NotificationType = { 'CaseApproved' : null } |
  { 'VerificationUpdate' : null } |
  { 'CaseRejected' : null } |
  { 'SupportSubmitted' : null } |
  { 'UnlockPurchased' : null } |
  { 'NewMessage' : null } |
  { 'ProudHeartReceived' : null };
export interface PageRequest { 'offset' : bigint, 'limit' : bigint }
export interface PaymentPublic {
  'id' : bigint,
  'status' : PaymentStatus,
  'createdAt' : Timestamp,
  'feeType' : FeeType,
  'amountCents' : USDCents,
  'caseId' : [] | [bigint],
  'stripeSessionId' : string,
  'paidBy' : UserId,
}
export type PaymentStatus = { 'Failed' : null } |
  { 'Confirmed' : null } |
  { 'Pending' : null };
export interface PlatformStats {
  'totalCases' : bigint,
  'totalSupportDistributed' : bigint,
  'totalHeroes' : bigint,
  'totalCompletedCases' : bigint,
}
export interface PrivacySettingsPublic {
  'profileVisibility' : string,
  'inAppNotificationsEnabled' : boolean,
  'countryVisibility' : boolean,
  'emailNotificationsEnabled' : boolean,
  'activityVisibility' : boolean,
  'caseUpdatesEnabled' : boolean,
}
export interface ProudHeart {
  'fromHelpSeeker' : UserId,
  'toHero' : UserId,
  'awardedAt' : Timestamp,
  'caseId' : bigint,
}
export type Result = { 'ok' : null } |
  { 'err' : Error };
export type ReviewStatus = { 'UnderReview' : null } |
  { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Submitted' : null } |
  { 'Completed' : null };
export type Role = { 'Hero' : null } |
  { 'HelpSeeker' : null } |
  { 'Admin' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface SupportProofPublic {
  'id' : bigint,
  'files' : Array<FileRef>,
  'status' : ReviewStatus,
  'heroId' : UserId,
  'referenceNumber' : [] | [string],
  'createdAt' : Timestamp,
  'adminNote' : [] | [string],
  'caseId' : bigint,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type USDCents = bigint;
export type UserId = Principal;
export interface UserPublic {
  'id' : UserId,
  'bio' : string,
  'timezone' : string,
  'preferredLanguage' : string,
  'country' : Country,
  'lastLoginAt' : bigint,
  'city' : string,
  'createdAt' : Timestamp,
  'role' : Role,
  'fullName' : string,
  'isActive' : boolean,
  'email' : string,
  'kycStatus' : KycStatus,
  'avatarRef' : [] | [FileRef],
  'phoneNumber' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSettingsPublic {
  'timezone' : string,
  'theme' : string,
  'weeklyDigest' : boolean,
  'emailNotifications' : boolean,
  'inAppNotifications' : boolean,
  'language' : string,
  'largerText' : boolean,
  'currencyDisplay' : string,
  'highContrast' : boolean,
  'reducedAnimations' : boolean,
}
export type VerificationStatus = { 'DocumentsSubmitted' : null } |
  { 'InstitutionVerified' : null } |
  { 'Unverified' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addCaseDocument' : ActorMethod<[bigint, FileRef], undefined>,
  'adminGrantCredits' : ActorMethod<[UserId, bigint, [] | [string]], undefined>,
  'adminUpdateKycStatus' : ActorMethod<[UserId, KycStatus], UserPublic>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'awardProudHeart' : ActorMethod<[bigint, UserId], undefined>,
  'banUser' : ActorMethod<[UserId], undefined>,
  'computeAchievements' : ActorMethod<[UserId], Array<Achievement>>,
  'confirmCreditPurchase' : ActorMethod<[string, bigint], undefined>,
  /**
   * / Confirm listing fee after Stripe session completes; records payment + wallet entry
   */
  'confirmListingFee' : ActorMethod<[string, [] | [bigint]], PaymentPublic>,
  /**
   * / Confirm unlock fee after Stripe session completes
   */
  'confirmUnlockFee' : ActorMethod<[string, bigint], PaymentPublic>,
  'createCase' : ActorMethod<
    [string, string, Category, Country, City, USDCents, Timestamp],
    bigint
  >,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createCreditPurchaseSession' : ActorMethod<[bigint, string, string], string>,
  /**
   * / Create a Stripe checkout session for the $1 listing fee
   */
  'createListingFeeSession' : ActorMethod<[string, string], string>,
  /**
   * / Create a Stripe checkout session for the $2 unlock fee
   */
  'createUnlockFeeSession' : ActorMethod<[bigint, string, string], string>,
  'dismissNotification' : ActorMethod<[bigint], boolean>,
  'getAllCases' : ActorMethod<[], Array<CasePublic>>,
  'getAllProofs' : ActorMethod<[], Array<SupportProofPublic>>,
  'getAllUsers' : ActorMethod<[], Array<UserPublic>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserPublic]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCaseDetail' : ActorMethod<[bigint], [] | [CasePublic]>,
  'getCaseSummary' : ActorMethod<[bigint], [] | [CaseSummary]>,
  'getConversationMessages' : ActorMethod<[bigint], Array<MessagePublic>>,
  'getHelpSeekerStats' : ActorMethod<[UserId], [] | [HelpSeekerStatsPublic]>,
  'getHeroStats' : ActorMethod<[UserId], [] | [HeroStatsPublic]>,
  'getLoginDevices' : ActorMethod<[], Array<LoginDevice>>,
  'getMyConversations' : ActorMethod<[], Array<ConversationPublic>>,
  'getMyNotifications' : ActorMethod<[], Array<NotificationPublic>>,
  /**
   * / Confirm unlock fee after Stripe session completes
   */
  'getMyProofs' : ActorMethod<[], Array<SupportProofPublic>>,
  'getMySupportedCases' : ActorMethod<[], Array<CaseSummary>>,
  'getMyTrustScore' : ActorMethod<[], bigint>,
  'getPendingPayments' : ActorMethod<[], Array<PaymentPublic>>,
  'getPlatformStats' : ActorMethod<[], PlatformStats>,
  'getPrivacySettings' : ActorMethod<[], [] | [PrivacySettingsPublic]>,
  'getProofsForCase' : ActorMethod<[bigint], Array<SupportProofPublic>>,
  'getProudHeartsForHero' : ActorMethod<[UserId], Array<ProudHeart>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTransactionHistory' : ActorMethod<[], Array<CreditTransaction>>,
  'getUnreadMessageCount' : ActorMethod<[], bigint>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUser' : ActorMethod<[UserId], [] | [UserPublic]>,
  'getUserSettings' : ActorMethod<[], [] | [UserSettingsPublic]>,
  'getWallet' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'isUnlocked' : ActorMethod<[bigint], boolean>,
  'listCases' : ActorMethod<[[] | [Category], PageRequest], Array<CaseSummary>>,
  'logoutAllOtherDevices' : ActorMethod<[], bigint>,
  'markNotificationAsRead' : ActorMethod<[bigint], boolean>,
  'registerUser' : ActorMethod<[string, string, Role], UserPublic>,
  'requestAccountDeletion' : ActorMethod<[], string>,
  'requestDataDownload' : ActorMethod<[], string>,
  'sendMessage' : ActorMethod<[UserId, [] | [bigint], string], MessagePublic>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitProof' : ActorMethod<[bigint, Array<FileRef>, [] | [string]], bigint>,
  'suspendUser' : ActorMethod<[UserId], undefined>,
  'switchRole' : ActorMethod<[Role], UserPublic>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unlockCase' : ActorMethod<[bigint], undefined>,
  'updatePrivacySettings' : ActorMethod<
    [string, boolean, boolean, boolean, boolean, boolean],
    PrivacySettingsPublic
  >,
  'updateProofStatus' : ActorMethod<
    [bigint, ReviewStatus, [] | [string]],
    undefined
  >,
  'updateUserProfile' : ActorMethod<
    [string, Country, [] | [FileRef]],
    UserPublic
  >,
  'updateUserProfileExtended' : ActorMethod<
    [string, Country, string, string, string, string, string, [] | [FileRef]],
    UserPublic
  >,
  'updateUserSettings' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      boolean,
      boolean,
      boolean,
      boolean,
      boolean,
      boolean,
    ],
    UserSettingsPublic
  >,
  'updateVerificationStatus' : ActorMethod<
    [bigint, VerificationStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];