packages: []
allowBuilds:
  '@biomejs/biome': true
  esbuild: true
  sharp: true
  tesseract.js: true
  workerd: true
onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - sharp
  - tesseract.js
  - workerd
